### ISSUE TITLE
Better errors with YAML action config files

### ISSUE THREAD

**Issue by johhnry** [ArtFXDev/silex_client#32]
- When the `commands` key is empty:

  ```yaml
  double:
  steps:
    init:
      index: 0
      label: "Logging"
      commands:
  ```

  Actual:

  ```
  dacite.exceptions.WrongTypeError: wrong value type for field "steps.commands" -
  should be "typing.Dict[str, silex_client.action.command_buffer.CommandBuffer]" instead of value "None" of type "NoneType"
  ```

  Expected: `Error: no commands given`

- If I have a `double.yml` configuration file for an action in the `config` folder with the following:

  ```yaml
  # double.yml

  test:
    steps:
      init:
        index: 0
        label: "Logging"
        commands:
          log_first:
            label: "First log"
            path: "silex_client.commands.utils.Log"
            parameters:
              message: "Initialization..."
              level: "info"
  ```

  The root key is not equal to the filename.

  Actual: 

  ```
  [action_query._initialize_buffer] Could not initialise the action: The resolved config is invalid (112)
  ```

  Expected: `Error: the top most key is not the same as the filename`

- When we have multiple commands with the same key name:

  ```yaml
  # double.yml

  double:
  steps:
    init:
      index: 0
      label: "Logging"
      commands:
        log_first:
          label: "First log"
          path: "silex_client.commands.utils.Log"
          parameters:
            message: "First log..."
            level: "info"

        log_first:
          label: "Second log"
          path: "silex_client.commands.utils.Log"
          parameters:
            message: "Second log..."
            level: "warn"
  ```

  Actual (actionquery json):

  ```json
  {
    "name": "double",
    "uuid": "eee7388c26d411ecb599ab3705c91dc2",
    "status": 2,
    "steps": {
      "init": {
        "name": "init",
        "index": 0,
        "status": 2,
        "label": "Logging",
        "hide": false,
      "tooltip": "",
        "commands": {
          "log_first": {
            "path": "silex_client.commands.utils.Log",
            "name": "log_first",
            "label": "Second log",
            "hide": false,
            "tooltip": "",
            "parameters": {
              "message": {
                "label": "Message",
                "type": "str",
                "value": "Second log..."
              },
              "level": {
                "label": "Level",
                "type": "str",
                "value": "warn"
              }
            },
            "uuid": "eee7388d26d411ecb599ab3705c91dc2",
            "status": 2
          }
        },
        "uuid": "eee7388f26d411ecb599ab3705c91dc2"
      }
    },
    // ...
  }
  ```

  Expected: `Warning: multiple command keys have the same name!`
