### ISSUE TITLE
Add or improve include directive in action Yaml

### ISSUE THREAD

**Issue by johhnry** [ArtFXDev/silex_client#420]
It would be nice to include pieces of yaml into another one like a mixin:

```yaml
# silex_coins.yml

silex_coins:
  index: 500
    commands:
      add_silex_coins:
        path: "silex_client.commands.user.silex_coins.AddSilexCoinsCommand"
          parameters:
            amount:
              value: 5
```

and inserting the step in the yaml:

```yaml
# publish.yml

publish:
  # ...
  steps:
    silex_coins: !include "silex_coins.yml"
```
