### ISSUE TITLE
Command retry count

### ISSUE THREAD

**Issue by johhnry** [ArtFXDev/silex_client#430]
A command that fails is annoying because it blocks the action execution.

It would be handy to add a `retry_count` property in the Yaml file to say that one command should be retried X times.

Like:

```yaml
silex_coins:
  commands:
    add_silex_coins:
      retry_count: 2
```
